import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { calculateRisk } from './riskMatrix'

/** Brand colours */
const NAVY  = [15, 37, 68]
const FLAME = [232, 87, 26]
const WHITE = [255, 255, 255]
const GREY  = [107, 114, 128]
const BG    = [248, 245, 238]

/** Risk row cell colour */
function ratingColor(rating) {
  switch (rating) {
    case 'EXTREME': return [220, 38, 38]
    case 'HIGH':    return [239, 68, 68]
    case 'MEDIUM':  return [245, 158, 11]
    case 'LOW':     return [34, 197, 94]
    default:        return [200, 200, 200]
  }
}

/**
 * Generate a risk assessment PDF
 * @param {object} ra — risk assessment data object
 * @param {string} [logoDataUrl] — base64 company logo (optional)
 */
export function exportRiskAssessmentPDF(ra, logoDataUrl = null) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })

  // Header bar
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, 297, 28, 'F')

  // Logo (if provided)
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 8, 4, 40, 20)
  }

  // Title block
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...WHITE)
  doc.text('RISK ASSESSMENT', logoDataUrl ? 60 : 10, 12)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...WHITE)
  doc.text(`Tushiya Conform · by Tushiya HS Consulting · ${ra.documentRef || 'REF-0001'}`, logoDataUrl ? 60 : 10, 18)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-NA')}`, 250, 12)

  // Meta table
  autoTable(doc, {
    startY: 32,
    head: [['Company', 'Site / Location', 'Work Activity', 'Assessor', 'Review Date']],
    body: [[
      ra.company || '',
      ra.site || '',
      ra.activity || '',
      ra.assessor || '',
      ra.reviewDate || '',
    ]],
    headStyles: { fillColor: BG, textColor: NAVY, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    theme: 'grid',
    margin: { left: 10, right: 10 },
  })

  // Legislation row
  doc.setFontSize(7)
  doc.setTextColor(...GREY)
  doc.text(`Legislation: ${(ra.legislation || []).join(' · ')}`, 10, doc.lastAutoTable.finalY + 5)

  // Hazard table
  const hazardRows = (ra.hazards || []).map(h => {
    const initial = calculateRisk(h.severity, h.likelihood)
    const residual = calculateRisk(h.residualSeverity, h.residualLikelihood)
    return [
      h.activity,
      h.hazard,
      `${h.severity}`,
      `${h.likelihood}`,
      initial.rating,
      (h.controls || []).join('\n'),
      `${h.residualSeverity}`,
      `${h.residualLikelihood}`,
      residual.rating,
      (h.ppe || []).join(', '),
    ]
  })

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [[
      'Activity', 'Hazard / Risk',
      'S', 'L', 'Initial Risk',
      'Control Measures',
      'S', 'L', 'Residual Risk',
      'PPE Required',
    ]],
    body: hazardRows,
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 7, valign: 'top' },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 40 },
      2: { cellWidth: 8, halign: 'center' },
      3: { cellWidth: 8, halign: 'center' },
      4: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
      5: { cellWidth: 65 },
      6: { cellWidth: 8, halign: 'center' },
      7: { cellWidth: 8, halign: 'center' },
      8: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
      9: { cellWidth: 40 },
    },
    didParseCell(data) {
      if (data.section === 'body' && (data.column.index === 4 || data.column.index === 8)) {
        const rating = data.cell.text[0]
        const [r, g, b] = ratingColor(rating)
        data.cell.styles.fillColor = [r, g, b]
        data.cell.styles.textColor = rating === 'LOW' ? [22, 101, 52] : WHITE
      }
    },
    theme: 'grid',
    margin: { left: 10, right: 10 },
  })

  // Signature block
  const sigY = doc.lastAutoTable.finalY + 10
  doc.setFontSize(8)
  doc.setTextColor(...NAVY)
  doc.text('Assessor Signature: ___________________________', 10, sigY)
  doc.text('Reviewer Signature: ___________________________', 100, sigY)
  doc.text('Approver Signature: ___________________________', 190, sigY)
  doc.text(`Date: _______________`, 10, sigY + 8)
  doc.text(`Date: _______________`, 100, sigY + 8)
  doc.text(`Date: _______________`, 190, sigY + 8)

  // Footer
  doc.setFontSize(6)
  doc.setTextColor(...GREY)
  doc.text(
    'Generated by Tushiya Conform · Tushiya HS Consulting · Walvis Bay & Windhoek, Namibia · oswald@tushiyahs.com · +264 81 260 9767 · tushiyahs.com',
    10, 208
  )

  doc.save(`${ra.documentRef || 'RiskAssessment'}_TushiyaConform.pdf`)
}

/**
 * Export Toolbox Talk as PDF
 */
export function exportToolboxTalkPDF(talk) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  doc.setFillColor(...NAVY)
  doc.rect(0, 0, 210, 30, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(...WHITE)
  doc.text('TOOLBOX TALK', 10, 14)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(`Tushiya Conform · by Tushiya HS Consulting`, 10, 21)

  // Content
  doc.setFontSize(13)
  doc.setTextColor(...NAVY)
  doc.setFont('helvetica', 'bold')
  doc.text(talk.title, 10, 40, { maxWidth: 190 })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(50, 50, 50)
  doc.text(talk.content || '', 10, 55, { maxWidth: 190 })

  // Attendance table
  autoTable(doc, {
    startY: 160,
    head: [['#', 'Name', 'Employee No.', 'Department', 'Signature', 'Date']],
    body: Array.from({ length: 15 }, (_, i) => [`${i + 1}`, '', '', '', '', '']),
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { minCellHeight: 8, fontSize: 8 },
    theme: 'grid',
    margin: { left: 10, right: 10 },
  })

  // Footer
  doc.setFontSize(6)
  doc.setTextColor(...GREY)
  doc.text(
    'Generated by Tushiya Conform · Tushiya HS Consulting · Walvis Bay & Windhoek, Namibia · oswald@tushiyahs.com · +264 81 260 9767 · tushiyahs.com',
    10, 290
  )

  doc.save(`${talk.id}_TushiyaConform_ToolboxTalk.pdf`)
}
